### ISSUE TITLE
Clicking on a menu leads to the first page

### ISSUE THREAD

**Issue by Brume-AL** [atari-legend/atari-legend#92]
Pretty sure it's in your to-do list, Nico 😉
When we click on a menu in the game details page, we reach the first page of the menu CD. Would it be possible to reach directly the menu instead of the first one of the list?

![Capture d’écran 2021-02-17 141759](https://user-images.githubusercontent.com/12120244/108210356-b8080d80-712b-11eb-8386-04bab36f7507.jpg)

**Comment by nguillaumin** [comment]
Thanks, I forgot about this. Initially I did not have an easy way to link to a specific menu. Should be good now.

**Comment by Brume-AL** [comment]
Thanks, that was fast and it works like a charm 👍👍👍

**Comment by Brume-AL** [comment]
Looks like it doesn't work in some cases.

https://menus.atarilegend.com/games/458

It works for Evil Force #2, Fuzion #13, Impact #13... But it doesn't work for DiskMap Crew #10 nor Dodgysoft #71

Thanks in advance Nico.

**Comment by nguillaumin** [comment]
Thanks for the extra testing. I fixed it again, but it's hard to get right so I hope there are no other edge cases...

**Comment by Brume-AL** [comment]
The issue is still there:
https://menus.atarilegend.com/menusets/software/379
If you press on Dodgysoft #70, it links to the first page of the menu set.

**Comment by nguillaumin** [comment]
Ah yes, I did not implement it there, only a link to the menu set (that's why the link was only on the set name, not including the number). But it makes more sense to link directly to the menu as well, should be fixed now.

**Comment by Brume-AL** [comment]
Perfect, works fine now 👍
Thank you Nicolas!
